[package]
name = "smart-panda"
version = "0.1.0"
authors = ["h3nnn4n <uber.renan@gmail.com>"]

[dependencies]
rand = "0.3.15"

[dependencies.sdl2]
  version = "0.31"
  default-features = false
  features = ["ttf","image","gfx","mixer"]
